classDiagram
  class Library {
    +add_book(book)
    +register_user(user)
    +create_loan(book, user)
  }

  class Book {
    +title: str
    +author: str
    +state: bool
    +mark_as_unavailable()
    +mark_as_available()
  }

  class User {
    +name: str
    +email: str
  }

  class Lone {
    +start_data
    +end_data
    +close_lone()
  }

  Library "1" o-- "0..*" Book
  Library "1" o-- "0..*" User
  Library "1" o-- "0..*" Lone
  Lone "1" --> "1" Book
  Lone "1" --> "1" User
